version:     "0001--13-Feb-2022"
copyright:   "2022"
author:      "Rayhan Adhisworo Jardine Hidayat"
title:       "OS221: Operating Systems 2022-1"
githublink:  "https://github.com/verehrungen/os221/"
myloglink:   "TXT/mylog.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
